### PR TITLE
Fix 'ioctl Method not implimented' errors in kismet when using wlan1 …

### PR DESCRIPTION
**Pull request by EyeOfGnut**
…drivers that only implement cfg80211 by turning on the option in the kernel config

When starting Kismet_server errors are thrown indicating that "get mode" from ioctl is not implemented, for example ath9k_htc devices. The kernel driver code doesn't seem to implement the older ioctl extensions in favor of ctl80211. By setting CONFIG_CFG80211_WEXT in the kernel, drivers that make use of cfg80211 will be able to inter-operate with the older userspace extensions. This also fixed the wifite issue of looping back to interface selection instead of starting capture, and iwconfig now shows information about the device instead of "no wireless extensions"

The second change is to enable CONFIG_FHANDLE, which resolves the issue with airmon_ng showing name_to_handle_at libudev errors when listing the interfaces.

### CODE REVIEW

**Comment by binkybear** [comment]
I usually set WEXT so I'm not sure what happened there.  Wasn't aware of FHANDLE. Thanks!

**Comment by binkybear** [comment]
I should probably note that 5.0 is Marshmallow (6.0) which isn't supported in NH.  If I remember correctly the branch i'm using for lollipop is: https://github.com/binkybear/kernel_msm/tree/android-msm-flo-3.4-lollipop-release

**Comment by EyeOfGnut** [comment]
Yeah, but with newinstaller-fj and the flo sepolicy you put there, and my kernel, it's been working fairly well, excepting the loss of the adb authorization messages. I add the computer's key to the auth keys file on the Nexus via terminal and it works fine.
 I forgot that ex5.0 was marshmallow only. Want me to make the change in the other branches and put in the pull requests?
On Dec 10, 2015 2:58 AM, binkybear notifications@github.com wrote:I should probably note that 5.0 is Marshmallow (6.0) which isn't supported in NH.  If I remember correctly the branch i'm using for lollipop is: https://github.com/binkybear/kernel_msm/tree/android-msm-flo-3.4-lollipop-release

**Comment by binkybear** [comment]
Thats great to hear you were able to get it running on Android 6. I've only tested Marshmallow on Nexus 5 and ran into same adb errors along with errors because of busybox not working due to symlink.  I'm a bit curious how exactly you fixed adb.

If you are interested in helping I could use a quick look at lollipop kernel also.  If not, I will get to it later.  Thanks for testing.

**Comment by EyeOfGnut** [comment]
I wouldn't say I "fixed" adb - I just cheated. To explain - 

I put a fresh install of MRA58V on my N7 (mostly because the update message annoyed me), and I'd used ADB to push TWRP and ElementalX5.05, and SuperSU, to root it. So I had my initial system's RSA pub key stored in the device's /data/misc/adb/adb_keys file.When I installed Nethunter with the newinstaller-fj branch (and the sepolicy contained therein), the prompt for allowing a new system disappeared along with the menu option for revoking all previous permissions. Now a new system would just time out when trying to connect with adb.
The initial system was a work laptop, which is the only 64-bit Kali install I have at the moment. Home is a mix of Win10, Ubuntu, and 32-bit Kali on an old laptop I saved from being recycled into... whatever silicon is recycled into. To let me tinker at home as well, I copied the pub key from ~/.android/adbkey.pub into the same adb_keys file on the device, and presto - access over adb from another system. Win10 is %USERPROFILE%.android\adbkey.pub. Same process worked for ADB over wifi, btw.

So overall, the process is pretty much the same as manually adding a public RSA key for SSH. I'm still looking for answers as to why the prompt and revocation disappeared, but my Google-Fu has failed me, and I haven't had the inspiration to poke into each and every change in the update-script from the nethunter installer to see exactly what's changed... after all, now I have access from all my systems, so it's more of a background itch instead of a priority.I was poking at compiling my own sepolicy to see if that was the cause, but I couldn't find a source for where yours came from and thus what, if anything, had been changed from default Marshmallow. The kernel I saw was your own ElementalX5 (thanks, kernel.txt), but where did you get the sepolicy?
I'd be happy to look at the Lollipop kernel - anything specific you're working on?

P.S. - I found an issue in the kalimenu script where the giskismet KML file was generated with a lower-case 'k' in the name, while the archiving of the captures in the zip file in f_kismet_save() pulled all files starting with an upper-case 'K' - and thus the kml file was never included in the zip archive, and was subsequently wiped. I put in a pull request for it earlier today.

```
On Thursday, December 10, 2015 7:01 PM, binkybear <notifications@github.com> wrote:
```

 Thats great to hear you were able to get it running on Android 6. I've only tested Marshmallow on Nexus 5 and ran into same adb errors along with errors because of busybox not working due to symlink. I'm a bit curious how exactly you fixed adb.If you are interested in helping I could use a quick look at lollipop kernel also. If not, I will get to it later. Thanks for testing.—

**Pull request merged**
